### ISSUE TITLE
Challenge 25 Execution Time

### ISSUE THREAD

**Issue by Doomtrain14** [manwar/perlweeklychallenge#24]
In **Challenge 25**, I think it is worth to note that Adam Russell's solution returned only **14 pokemon names** from the list. (Not sure if I ran the script correctly or missed anything)

`machamp-petilil-lunatone-exeggcute-emboar-registeel-loudred-darmanitan-nosepass-simisear-rufflet-tyrogue-emolga-audino 105`

**Comment by manwar** [comment]
I am tagging @kianmeng for the comment :-)

**Comment by kianmeng** [comment]
@Doomtrain14 You're correct and it seemed to be returning 14 items. Good catch!
```bash
$ time perl challenge-025/adam-russell/perl5/ch-1.pl 
machamp-petilil-lunatone-exeggcute-emboar-registeel-loudred-darmanitan-nosepass-simisear-rufflet-tyrogue-emolga-audino 105

real    0m0.568s
user    0m0.560s
sys     0m0.008s
```

Tagging @adamcrussell.
Adam, you want to update and fix the code to get the maximum number of chain, which is 23 names?

**Comment by adamcrussell** [comment]
Sure! Based on my (tired?) reading of the problem statement I was trying to maximize number of characters in the names and not path length. I’ll make a change. Surely it’ll be just nearly as fast though.

Need a little time to do this, maybe not until late tonight or tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by manwar** [comment]
Hopefully it is safe to close by now.
